-- MySQL Script generated by MySQL Workbench
-- Sun Apr 14 22:44:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dizziness_syst
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dizziness_syst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dizziness_syst` DEFAULT CHARACTER SET utf8 ;
USE `dizziness_syst` ;

-- -----------------------------------------------------
-- Table `dizziness_syst`.`Profesional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizziness_syst`.`Profesional` (
  `idProfesional` INT NOT NULL AUTO_INCREMENT,
  `tipoMatricula` VARCHAR(45) NOT NULL,
  `matricula` INT NOT NULL,
  PRIMARY KEY (`idProfesional`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizziness_syst`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizziness_syst`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `tipoDoc` VARCHAR(22) NOT NULL,
  `documento` INT NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `Profesional_idProfesional` INT NOT NULL,
  PRIMARY KEY (`idPaciente`),
  INDEX `fk_Paciente_Profesional1_idx` (`Profesional_idProfesional` ASC),
  CONSTRAINT `fk_Paciente_Profesional1`
    FOREIGN KEY (`Profesional_idProfesional`)
    REFERENCES `dizziness_syst`.`Profesional` (`idProfesional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizziness_syst`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizziness_syst`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizziness_syst`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizziness_syst`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizziness_syst`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizziness_syst`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(60) NOT NULL,
  `Rol_idRol` INT NOT NULL,
  `Paciente_idPaciente` INT NULL,
  `Profesional_idProfesional` INT NULL,
  `Administrador_idAdministrador` INT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Rol1_idx` (`Rol_idRol` ASC),
  INDEX `fk_Usuario_Paciente1_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_Usuario_Profesional1_idx` (`Profesional_idProfesional` ASC),
  INDEX `fk_Usuario_Administrador1_idx` (`Administrador_idAdministrador` ASC),
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `dizziness_syst`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `dizziness_syst`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Profesional1`
    FOREIGN KEY (`Profesional_idProfesional`)
    REFERENCES `dizziness_syst`.`Profesional` (`idProfesional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `dizziness_syst`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizziness_syst`.`Crisis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizziness_syst`.`Crisis` (
  `idCrisis` INT NOT NULL AUTO_INCREMENT,
  `brusco` TINYINT NOT NULL,
  `lento` TINYINT NOT NULL,
  `inicio` VARCHAR(200) NOT NULL,
  `duracion` VARCHAR(45) NOT NULL,
  `frecuencia` VARCHAR(200) NOT NULL,
  `factoresDesenc` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idCrisis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizziness_syst`.`Estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizziness_syst`.`Estudio` (
  `idEstudio` INT NOT NULL AUTO_INCREMENT,
  `otoscopia` VARCHAR(200) NULL,
  `audiologico` VARCHAR(200) NULL,
  `videonistamografia` VARCHAR(200) NULL,
  `tac` VARCHAR(200) NULL,
  `otro` VARCHAR(200) NULL,
  PRIMARY KEY (`idEstudio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizziness_syst`.`Ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizziness_syst`.`Ingreso` (
  `idIngreso` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `edad` INT NOT NULL,
  `profesion` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `derivacion` VARCHAR(45) NOT NULL,
  `motivoConsulta` VARCHAR(200) NOT NULL,
  `diagnostico` VARCHAR(100) NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `Crisis_idCrisis` INT NOT NULL,
  `Estudio_idEstudio` INT NOT NULL,
  PRIMARY KEY (`idIngreso`),
  INDEX `fk_Ingreso_Paciente1_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_Ingreso_Crisis1_idx` (`Crisis_idCrisis` ASC),
  INDEX `fk_Ingreso_Estudio1_idx` (`Estudio_idEstudio` ASC),
  CONSTRAINT `fk_Ingreso_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `dizziness_syst`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingreso_Crisis1`
    FOREIGN KEY (`Crisis_idCrisis`)
    REFERENCES `dizziness_syst`.`Crisis` (`idCrisis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingreso_Estudio1`
    FOREIGN KEY (`Estudio_idEstudio`)
    REFERENCES `dizziness_syst`.`Estudio` (`idEstudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizziness_syst`.`Sintoma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizziness_syst`.`Sintoma` (
  `idSintoma` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSintoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizziness_syst`.`Ingreso_has_Sintoma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizziness_syst`.`Ingreso_has_Sintoma` (
  `Ingreso_idIngreso` INT NOT NULL,
  `Sintoma_idSintoma` INT NOT NULL,
  PRIMARY KEY (`Ingreso_idIngreso`, `Sintoma_idSintoma`),
  INDEX `fk_Ingreso_has_Sintoma_Sintoma1_idx` (`Sintoma_idSintoma` ASC),
  INDEX `fk_Ingreso_has_Sintoma_Ingreso1_idx` (`Ingreso_idIngreso` ASC),
  CONSTRAINT `fk_Ingreso_has_Sintoma_Ingreso1`
    FOREIGN KEY (`Ingreso_idIngreso`)
    REFERENCES `dizziness_syst`.`Ingreso` (`idIngreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingreso_has_Sintoma_Sintoma1`
    FOREIGN KEY (`Sintoma_idSintoma`)
    REFERENCES `dizziness_syst`.`Sintoma` (`idSintoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizziness_syst`.`Sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizziness_syst`.`Sesion` (
  `idSesion` INT NOT NULL AUTO_INCREMENT,
  `nroSesion` INT NOT NULL,
  `fechaActivacion` DATE NOT NULL,
  `repeticiones` INT NOT NULL,
  `fechaRealizacion` DATE NULL,
  `Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`idSesion`),
  INDEX `fk_Sesion_Paciente1_idx` (`Paciente_idPaciente` ASC),
  CONSTRAINT `fk_Sesion_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `dizziness_syst`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizziness_syst`.`Ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizziness_syst`.`Ejercicio` (
  `idEjercicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `video` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idEjercicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dizziness_syst`.`Asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dizziness_syst`.`Asignacion` (
  `idAsignacion` INT NOT NULL AUTO_INCREMENT,
  `repeticiones` INT NOT NULL,
  `estado` TINYINT NOT NULL,
  `Sesion_idSesion` INT NOT NULL,
  `Ejercicio_idEjercicio` INT NOT NULL,
  PRIMARY KEY (`idAsignacion`),
  INDEX `fk_Actividad_Sesion1_idx` (`Sesion_idSesion` ASC),
  INDEX `fk_Asignacion_Ejercicio1_idx` (`Ejercicio_idEjercicio` ASC),
  CONSTRAINT `fk_Actividad_Sesion1`
    FOREIGN KEY (`Sesion_idSesion`)
    REFERENCES `dizziness_syst`.`Sesion` (`idSesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Ejercicio1`
    FOREIGN KEY (`Ejercicio_idEjercicio`)
    REFERENCES `dizziness_syst`.`Ejercicio` (`idEjercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
